# fly.toml app configuration file generated for polyglotize on 2024-12-23T17:26:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'polyglotize'
primary_region = 'hkg'
swap_size_mb = 512

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
